owner: jan64x
repo: upptime

sites:
  - name: Main site
    url: https://janpetrlik.com
  - name: Personal GitLab
    url: https://git.janpetrlik.com
  - name: SearXNG instance
    url: https://search.janpetrlik.com
  - name: Sharkey instance
    url: https://fedi.janpetrlik.com

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Welcome to yuichi's Upptime instance!"
  introMessage: This is my personal Upptime instance to monitor my homelab until I find a better solution.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
